# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jennifer Hiew - Portfolio
email: jenhiew21@gmail.com
description: Jennifer Hiew - Portfolio
baseurl: "/hyperspace-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url: 
etsy_url: https://www.etsy.com/ca/shop/Virize
facebook_url: https://www.facebook.com/VirizeArt/
github_url: https://github.com/virize
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/jenniferhiew
pinterest_url: 
slack_url: 
tumblr_url: http://virize.tumblr.com
twitter_url: https://twitter.com/virizeze

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username:
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
